name: Daily Commit

on:
  schedule:
    - cron: '0 3 * * *' # Runs every day at 3:00 am

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name 'PeitaoPeng'
        git config --global user.email 'peitaopeng@hotmail.com'

    - name: Add untracked files
      run: git add --all

    - name: Commit changes
      run: |
        current_time=$(date)
        git commit -m "Daily commit for $current_time"

    - name: Push changes
      run: git push origin HEAD
      env:
        GITHUB_TOKEN: ${{ secrets.Desktop }}

